### ISSUE TITLE
Unable to launch compiled binaries

### ISSUE THREAD

**Issue by xavmag** [cstom4994/SourceEngineRebuild#1]
When I launch the compiled binaries with hl2 assets I receive "Engine Error" window with the "Could not load library client. If that doesn't work, verify the cache." message. Neither precompiled nor manually compiled binaries will work.

**Comment by cstom4994** [comment]
Hello, The compiled binaries of hl2 client is not provided in precompiled packages which was only provide CStrike's compiled binaries.
It's can be solved by manually compile the source code with BUILD_HL2=1 ( in src/CMakeLists.txt line 91 ) then it will compile hl2's DLLs
